version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.0
  # different jobs are called later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: cimg/node:lts
    steps:
      - node/install
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - node/install
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Unit Tests
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - node/install
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Linting
          command: npm run lint
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
      - lint
